### ISSUE TITLE
3Dモデルファイルがmegarover_samplesパッケージに依存している

### ISSUE THREAD

**Issue by atinfinity** [vstoneofficial/megarover3_ros#1]
@matsuyama-v <https://github.com/vstoneofficial/megarover3_ros/blob/0b84ee2d8e92138e680dc50938ad95b2287eef9b/robots/megarover.urdf.xacro>を読むと

```xml
<xacro:include filename="$(find megarover_samples)/urdf/body/body.urdf.xacro"/>
```

となっており、megarover_samplesパッケージに依存しているようですが意図通りでしょうか？[package.xml](https://github.com/vstoneofficial/megarover3_ros/blob/0b84ee2d8e92138e680dc50938ad95b2287eef9b/package.xml)を読む限りは依存はしていないようです。

また、関連して<https://github.com/vstoneofficial/megarover3_ros/blob/0b84ee2d8e92138e680dc50938ad95b2287eef9b/robots/megarover.urdf>でも

```xml
<mesh filename="/home/rover/catkin_ws/src/megarover_samples/meshes/DAE/megarover.dae"/>
```

という記述があり、megarover_samplesパッケージに依存しているように見受けられます。

**Comment by matsuyama-v** [comment]
ご指摘ありがとうございます。
メガローバーVer2.1用の記述およびファイルが残っていたのもので、メッシュファイルを削除、launchはメッシュファイルを参照しない形に書き換えました。

**Comment by atinfinity** [comment]
対応ありがとうございました。
